---
title: "gsx2 figure 1"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Install all packages 

```{r}
suppressPackageStartupMessages({
  install.packages("BiocManager")
  BiocManager::install("multtest")
  install.packages("Seurat")
  install.packages("patchwork")
  install.packages('gtools')
  if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
  if (!require(ReactomeGSA))
    BiocManager::install("ReactomeGSA")
  BiocManager::install('BSgenome.Drerio.UCSC.danRer11')
  BiocManager::install('SparseArray')
  install.packages('Signac')
  BiocManager::install('slingshot')
  BiocManager::install('SingleCellExperiment')
  install.packages("ggrepel")
  install.packages("dplyr")
  BiocManager::install('GenomeInfoDb')
  BiocManager::install('MatrixGenerics')
  BiocManager::install('matrixStats')
  BiocManager::install('DelayedMatrixStats')
})
```

Load libraries

```{r}
library(gtools)
library(Seurat)
library(Signac)
library(ggplot2)
```

Create RNA UMAP for 36 hpf
```{r}
olig2_36hpf <- readRDS("/Users/kimarena16/Desktop/data/olig2_36hpf.RDS")
DefaultAssay(olig2_36hpf) <- "SCT"
umap_plot_36hpf <- DimPlot(olig2_36hpf, label = TRUE) #label=false if you don't want labels on the plot
umap_plot_36hpf
ggsave("36hpf_labeled_umap_2.pdf", plot = umap_plot_36hpf, width = 11, height = 7, dpi = 300, units = "in")
```
Create RNA UMAP for 48 hpf
```{r}
olig2_48hpf <- readRDS("/Users/kimarena16/Desktop/data/olig2_48hpf.RDS")
DefaultAssay(olig2_48hpf) <- "SCT"
umap_plot_48hpf <- DimPlot(olig2_48hpf, label = TRUE) #label=false if you don't want labels on the plot
umap_plot_48hpf
ggsave("48hpf_labeled_umap_2.pdf", plot = umap_plot_48hpf, width = 11, height = 7, dpi = 300, units = "in")
```
Create ATAC UMAP for 36 hpf

```{r}
DefaultAssay(olig2_36hpf) <- "peaks"
ATAC_UMAP_36 <- DimPlot(olig2_36hpf, reduction = "umap.atac", label = TRUE, label.size = 5, repel = TRUE)
ATAC_UMAP_36
ggsave(filename="36hpf_ATAC_UMAP.pdf",plot=ATAC_UMAP_36, width = 11, height = 7, dpi = 300, units = "in")
```

Creat ATAC UMAP for 48 hpf

```{r}
DefaultAssay(olig2_48hpf) <- "peaks"
ATAC_UMAP_48 <- DimPlot(olig2_48hpf, reduction = "umap.atac", label = TRUE, label.size = 5, repel = TRUE)
ATAC_UMAP_48
ggsave(filename="48hpf_ATAC_UMAP.pdf",plot=ATAC_UMAP_48, width = 11, height = 7, dpi = 300, units = "in")
```

Trajectory Analysis 36 hpf NP1->OPC and NP1->MN1

```{r}
library(SingleCellExperiment)
library(dplyr)
library(GenomicRanges)
library(slingshot)
library(ggplot2)
library(ggrepel)

coords <- Embeddings(olig2_36hpf, "umap.rna")
umap_df <- as.data.frame(coords)
umap_df$cluster <- Idents(olig2_36hpf)
colnames(umap_df)[1:2] <- c("UMAP_1", "UMAP_2")

opc_lineage <- c("NP1","pre-OPC","OPC")
mn_lineage  <- c("NP1","pre-MNs","MN1")
traj_clusters <- c(opc_lineage, mn_lineage)

filter_lineage_cells <- function(lineage_clusters, umap_df, threshold_frac = 0.02, max_distance = 5){
  keep_cells <- c()
  for(cl in lineage_clusters){
    cl_coords <- umap_df[umap_df$cluster == cl, 1:2, drop = FALSE]
    center <- colMeans(cl_coords)
    distances <- sqrt(rowSums((cl_coords - center)^2))
    
    keep <- (distances < quantile(distances, probs = 1 - threshold_frac)) & (distances < max_distance)
    keep_cells <- c(keep_cells, rownames(cl_coords)[keep])
  }
  return(unique(keep_cells))
}

cells_opc <- filter_lineage_cells(opc_lineage, umap_df, threshold_frac = 0.02, max_distance = 5)
cells_mn  <- filter_lineage_cells(mn_lineage, umap_df, threshold_frac = 0.02, max_distance = 5)
cells_filtered <- unique(c(cells_opc, cells_mn))

umap_df_filtered <- umap_df[cells_filtered, ]
coords_filtered <- coords[cells_filtered, ]

run_lineage <- function(clusters_subset){
  sce <- SingleCellExperiment(
    assays = list(dummy = matrix(0, nrow = 1, ncol = nrow(coords_filtered))),
    colData = data.frame(cluster = umap_df_filtered$cluster),
    reducedDims = SimpleList(RNA_UMAP = coords_filtered)
  )
  sce <- sce[, sce$cluster %in% clusters_subset]
  sce$cluster <- factor(sce$cluster)
  
  sce <- slingshot(
    sce,
    clusterLabels = "cluster",
    reducedDim = "RNA_UMAP",
    start.clus = "NP1",
    stretch = 0,
    approx_points = 200
  )
  
  curve <- SlingshotDataSet(sce)@curves[[1]]
  df <- as.data.frame(curve$s)
  colnames(df) <- c("UMAP_1","UMAP_2")
  
  np1_coords <- coords_filtered[umap_df_filtered$cluster == "NP1", , drop = FALSE]
  np1_center <- colMeans(np1_coords)
  df[1, ] <- np1_center
  
  return(df)
}

df_opc <- run_lineage(opc_lineage)
df_mn  <- run_lineage(mn_lineage)

cluster_levels <- levels(Idents(olig2_36hpf))
seurat_colors <- scales::hue_pal()(length(cluster_levels))  # default Seurat colors
names(seurat_colors) <- cluster_levels

umap_df_filtered$color <- ifelse(
  umap_df_filtered$cluster %in% traj_clusters,
  as.character(umap_df_filtered$cluster),
  "Other"
)
plot_colors <- c(seurat_colors[traj_clusters], Other = "grey80")

label_df <- aggregate(cbind(UMAP_1, UMAP_2) ~ cluster, data = umap_df_filtered, FUN = mean)
label_df <- label_df[label_df$cluster %in% traj_clusters, ]

trajectory <- ggplot(umap_df_filtered, aes(x = UMAP_1, y = UMAP_2)) +
  geom_point(aes(color = color), size = 1) +
  geom_path(data = df_opc, aes(x = UMAP_1, y = UMAP_2), color = "black", size = 1) +
  geom_path(data = df_mn, aes(x = UMAP_1, y = UMAP_2), color = "black", size = 1) +
  scale_color_manual(values = plot_colors) +
  geom_text_repel(data = label_df, aes(label = cluster), size = 4) +
  theme_classic() +
  theme(aspect.ratio = 1, legend.position = "none")
trajectory
ggsave(filename="36hpf_trajectory.pdf",plot=trajectory, width = 11, height = 7, dpi = 300, units = "in")

```


